<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by lupdate-c. To update this file, run the 'lupdate-c' command below. -->
<!-- lupdate-c -i "main.c" -o "lupdate_en.ts" -l "en_US" -->
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<context>
    <name>Main</name>
    <message>
        <location filename="main.c" line="17"/>
        <source>L&amp;anguage:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.c" line="21"/>
        <source>&amp;Up</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.c" line="25"/>
        <source>&amp;Down</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.c" line="29"/>
        <source>&amp;Left</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.c" line="33"/>
        <source>&amp;Right</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.c" line="37"/>
        <source>E&amp;xit</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.c" line="41"/>
        <source>&amp;File</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.c" line="45"/>
        <source>Ctrl+Q</source>
        <comment>Quit</comment>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
