// Generated by libqt6c uic. To update this file, edit the .ui file in
// Qt Creator/Designer, and then run the 'uic-c' command below.
//
// uic-c -i design.ui -o design.h -e

#include <libqt6c.h>

struct MainWindowUi;
typedef struct MainWindowUi MainWindowUi;

struct MainWindowUi {
    QMainWindow* MainWindow;
    QWidget* centralwidget;
    QGridLayout* gridLayout;
    KEditListWidget* keditlistwidget;
    QTabWidget* tabWidget;
    QWidget* tab;
    QFormLayout* formLayout;
    QLabel* label;
    KComboBox* kcombobox;
    QLabel* label_2;
    KPluralHandlingSpinBox* kpluralhandlingspinbox;
    QLabel* label_3;
    KLineEdit* klineedit;
    QWidget* tab_2;
    QVBoxLayout* verticalLayout_2;
    QVBoxLayout* verticalLayout_3;
    QFormLayout* formLayout_2;
    KFontRequester* kfontrequester;
    KLed* kled;
    QMenuBar* menubar;
    QMenu* menu_File;
    QStatusBar* statusbar;
    QDockWidget* dockWidget;
    QWidget* dockWidgetContents;
    QVBoxLayout* verticalLayout;
    KDatePicker* kdatepicker;
    QAction* action_New;
    QAction* actionE_xit;
};

// Retranslate reapplies all text translations
static void retranslate_main_window(MainWindowUi* ui) {
    const char* text0 = q_coreapplication_translate("MainWindow", "MainWindow");
    q_mainwindow_set_window_title(ui->MainWindow, text0);
    libqt_free(text0);
    const char* text1 = q_coreapplication_translate("MainWindow", "&New...");
    q_action_set_text(ui->action_New, text1);
    libqt_free(text1);
    const char* text2 = q_coreapplication_translate("MainWindow", "E&xit");
    q_action_set_text(ui->actionE_xit, text2);
    libqt_free(text2);
    const char* text3 = q_coreapplication_translate("MainWindow", "Ctrl+Q");
    QKeySequence* actionE_xit_shortcut = q_keysequence_new2(text3);
    libqt_free(text3);
    q_action_set_shortcut(ui->actionE_xit, actionE_xit_shortcut);
    q_keysequence_delete(actionE_xit_shortcut);
    const char* keditlistwidget_items0 = q_coreapplication_translate("MainWindow", "Item 1");
    const char* keditlistwidget_items1 = q_coreapplication_translate("MainWindow", "Item 2");
    const char* keditlistwidget_items2 = q_coreapplication_translate("MainWindow", "Item 3");
    const char* keditlistwidget_items[] = {keditlistwidget_items0, keditlistwidget_items1, keditlistwidget_items2, NULL};
    k_editlistwidget_set_items(ui->keditlistwidget, keditlistwidget_items);
    libqt_free(keditlistwidget_items0);
    libqt_free(keditlistwidget_items1);
    libqt_free(keditlistwidget_items2);
    const char* text4 = q_coreapplication_translate("MainWindow", "Tab 1");
    q_tabwidget_set_tab_text(ui->tabWidget, q_tabwidget_index_of(ui->tabWidget, ui->tab), text4);
    libqt_free(text4);
    const char* text5 = q_coreapplication_translate("MainWindow", "Dropdown:");
    q_label_set_text(ui->label, text5);
    libqt_free(text5);
    const char* text6 = q_coreapplication_translate("MainWindow", "First");
    k_combobox_set_item_text(ui->kcombobox, 0, text6);
    libqt_free(text6);
    const char* text7 = q_coreapplication_translate("MainWindow", "Second");
    k_combobox_set_item_text(ui->kcombobox, 1, text7);
    libqt_free(text7);
    const char* text8 = q_coreapplication_translate("MainWindow", "Number:");
    q_label_set_text(ui->label_2, text8);
    libqt_free(text8);
    const char* text9 = q_coreapplication_translate("MainWindow", "Input:");
    q_label_set_text(ui->label_3, text9);
    libqt_free(text9);
    const char* text10 = q_coreapplication_translate("MainWindow", "Tab 2");
    q_tabwidget_set_tab_text(ui->tabWidget, q_tabwidget_index_of(ui->tabWidget, ui->tab_2), text10);
    libqt_free(text10);
    const char* text11 = q_coreapplication_translate("MainWindow", "Sample text");
    k_fontrequester_set_sample_text(ui->kfontrequester, text11);
    libqt_free(text11);
    const char* text12 = q_coreapplication_translate("MainWindow", "&File");
    q_menu_set_title(ui->menu_File, text12);
    libqt_free(text12);
    const char* text13 = q_coreapplication_translate("MainWindow", "Dock Title");
    q_dockwidget_set_window_title(ui->dockWidget, text13);
    libqt_free(text13);
}

// new_main_window_ui creates all the Qt objects for MainWindowUi
static MainWindowUi* new_main_window_ui() {
    MainWindowUi* ui = (MainWindowUi*)malloc(sizeof(MainWindowUi));

    ui->MainWindow = q_mainwindow_new2();
    q_mainwindow_set_object_name(ui->MainWindow, "MainWindow");
    q_mainwindow_resize(ui->MainWindow, 800, 600);

    ui->action_New = q_action_new4(ui->MainWindow);
    q_action_set_object_name(ui->action_New, "action_New");

    ui->actionE_xit = q_action_new4(ui->MainWindow);
    q_action_set_object_name(ui->actionE_xit, "actionE_xit");

    ui->centralwidget = q_widget_new(ui->MainWindow);
    q_widget_set_object_name(ui->centralwidget, "centralwidget");

    ui->gridLayout = q_gridlayout_new(ui->centralwidget);
    q_gridlayout_set_object_name(ui->gridLayout, "gridLayout");

    ui->keditlistwidget = k_editlistwidget_new(ui->centralwidget);
    k_editlistwidget_set_object_name(ui->keditlistwidget, "keditlistwidget");

    q_gridlayout_add_widget2(ui->gridLayout, ui->keditlistwidget, 0, 1);

    ui->tabWidget = q_tabwidget_new(ui->centralwidget);
    q_tabwidget_set_object_name(ui->tabWidget, "tabWidget");

    ui->tab = q_widget_new2();
    q_widget_set_object_name(ui->tab, "tab");

    ui->formLayout = q_formlayout_new(ui->tab);
    q_formlayout_set_object_name(ui->formLayout, "formLayout");

    ui->label = q_label_new(ui->tab);
    q_label_set_object_name(ui->label, "label");
    q_formlayout_set_widget(ui->formLayout, 0, QFORMLAYOUT_ITEMROLE_LABELROLE, ui->label);

    ui->kcombobox = k_combobox_new(ui->tab);
    k_combobox_set_object_name(ui->kcombobox, "kcombobox");
    k_combobox_add_item(ui->kcombobox, "");
    k_combobox_add_item(ui->kcombobox, "");
    q_formlayout_set_widget(ui->formLayout, 0, QFORMLAYOUT_ITEMROLE_FIELDROLE, ui->kcombobox);

    ui->label_2 = q_label_new(ui->tab);
    q_label_set_object_name(ui->label_2, "label_2");
    q_formlayout_set_widget(ui->formLayout, 1, QFORMLAYOUT_ITEMROLE_LABELROLE, ui->label_2);

    ui->kpluralhandlingspinbox = k_pluralhandlingspinbox_new(ui->tab);
    k_pluralhandlingspinbox_set_object_name(ui->kpluralhandlingspinbox, "kpluralhandlingspinbox");
    q_formlayout_set_widget(ui->formLayout, 1, QFORMLAYOUT_ITEMROLE_FIELDROLE, ui->kpluralhandlingspinbox);

    ui->label_3 = q_label_new(ui->tab);
    q_label_set_object_name(ui->label_3, "label_3");
    q_formlayout_set_widget(ui->formLayout, 2, QFORMLAYOUT_ITEMROLE_LABELROLE, ui->label_3);

    ui->klineedit = k_lineedit_new(ui->tab);
    k_lineedit_set_object_name(ui->klineedit, "klineedit");
    q_formlayout_set_widget(ui->formLayout, 2, QFORMLAYOUT_ITEMROLE_FIELDROLE, ui->klineedit);

    q_tabwidget_add_tab(ui->tabWidget, ui->tab, "");

    ui->tab_2 = q_widget_new2();
    q_widget_set_object_name(ui->tab_2, "tab_2");

    ui->verticalLayout_2 = q_vboxlayout_new(ui->tab_2);
    q_vboxlayout_set_object_name(ui->verticalLayout_2, "verticalLayout_2");

    ui->verticalLayout_3 = q_vboxlayout_new2();
    q_vboxlayout_set_object_name(ui->verticalLayout_3, "verticalLayout_3");

    ui->formLayout_2 = q_formlayout_new2();
    q_formlayout_set_object_name(ui->formLayout_2, "formLayout_2");

    ui->kfontrequester = k_fontrequester_new(ui->tab_2);
    k_fontrequester_set_object_name(ui->kfontrequester, "kfontrequester");
    q_formlayout_set_widget(ui->formLayout_2, 0, QFORMLAYOUT_ITEMROLE_LABELROLE, ui->kfontrequester);

    q_vboxlayout_add_layout(ui->verticalLayout_3, ui->formLayout_2);

    ui->kled = k_led_new(ui->tab_2);
    k_led_set_object_name(ui->kled, "kled");
    k_led_set_minimum_size2(ui->kled, 40, 40);
    k_led_set_maximum_size2(ui->kled, 50, 50);
    k_led_set_shape(ui->kled, KLED_SHAPE_CIRCULAR);
    QColor* kled_color0 = q_color_new5(85, 85, 85);
    k_led_set_color(ui->kled, kled_color0);
    q_color_delete(kled_color0);

    q_vboxlayout_add_widget(ui->verticalLayout_3, ui->kled);

    q_vboxlayout_add_layout(ui->verticalLayout_2, ui->verticalLayout_3);

    q_tabwidget_add_tab(ui->tabWidget, ui->tab_2, "");
    q_gridlayout_add_widget2(ui->gridLayout, ui->tabWidget, 0, 0);
    q_mainwindow_set_central_widget(ui->MainWindow, ui->centralwidget);

    ui->menubar = q_menubar_new(ui->MainWindow);
    q_menubar_set_object_name(ui->menubar, "menubar");
    q_menubar_set_geometry(ui->menubar, 0, 0, 800, 27);

    ui->menu_File = q_menu_new(ui->menubar);
    q_menu_set_object_name(ui->menu_File, "menu_File");
    q_mainwindow_set_menu_bar(ui->MainWindow, ui->menubar);

    ui->statusbar = q_statusbar_new(ui->MainWindow);
    q_statusbar_set_object_name(ui->statusbar, "statusbar");
    q_mainwindow_set_status_bar(ui->MainWindow, ui->statusbar);

    ui->dockWidget = q_dockwidget_new(ui->MainWindow);
    q_dockwidget_set_object_name(ui->dockWidget, "dockWidget");
    q_mainwindow_add_dock_widget(ui->MainWindow, /* enum Qt__DockWidgetArea */ 1, ui->dockWidget);

    ui->dockWidgetContents = q_widget_new2();
    q_widget_set_object_name(ui->dockWidgetContents, "dockWidgetContents");

    ui->verticalLayout = q_vboxlayout_new(ui->dockWidgetContents);
    q_vboxlayout_set_object_name(ui->verticalLayout, "verticalLayout");

    ui->kdatepicker = k_datepicker_new(ui->dockWidgetContents);
    k_datepicker_set_object_name(ui->kdatepicker, "kdatepicker");

    q_vboxlayout_add_widget(ui->verticalLayout, ui->kdatepicker);
    q_dockwidget_set_widget(ui->dockWidget, ui->dockWidgetContents);

    q_menubar_add_action(ui->menubar, q_menu_menu_action(ui->menu_File));
    q_menu_add_action(ui->menu_File, ui->action_New);
    q_menu_add_separator(ui->menu_File);
    q_menu_add_action(ui->menu_File, ui->actionE_xit);

    retranslate_main_window(ui);

    q_tabwidget_set_current_index(ui->tabWidget, 0);

    return ui;
}
