// Generated by libqt6c uic. To update this file, edit the .ui file in
// Qt Creator/Designer, and then run the 'uic-c' command below.
//
// uic-c -i design.ui -o design.h

#include <libqt6c.h>

struct MainWindowUi;
typedef struct MainWindowUi MainWindowUi;

struct MainWindowUi {
    QMainWindow* MainWindow;
    QWidget* centralwidget;
    QGridLayout* gridLayout;
    QTabWidget* tabWidget;
    QWidget* tab;
    QFormLayout* formLayout;
    QLabel* label;
    QComboBox* comboBox;
    QLabel* label_2;
    QSpinBox* spinBox;
    QWidget* tab_2;
    QTreeWidget* treeWidget;
    QMenuBar* menubar;
    QMenu* menu_File;
    QStatusBar* statusbar;
    QDockWidget* dockWidget;
    QWidget* dockWidgetContents;
    QVBoxLayout* verticalLayout;
    QCalendarWidget* calendarWidget;
    QAction* action_New;
    QAction* actionE_xit;
};

// Retranslate reapplies all text translations
static void retranslate_main_window(MainWindowUi* ui) {
    const char* text0 = q_coreapplication_translate("MainWindow", "MainWindow");
    q_mainwindow_set_window_title(ui->MainWindow, text0);
    libqt_free(text0);
    const char* text1 = q_coreapplication_translate("MainWindow", "&New...");
    q_action_set_text(ui->action_New, text1);
    libqt_free(text1);
    const char* text2 = q_coreapplication_translate("MainWindow", "E&xit");
    q_action_set_text(ui->actionE_xit, text2);
    libqt_free(text2);
    const char* text3 = q_coreapplication_translate("MainWindow", "Ctrl+Q");
    QKeySequence* actionE_xit_shortcut = q_keysequence_new2(text3);
    libqt_free(text3);
    q_action_set_shortcut(ui->actionE_xit, actionE_xit_shortcut);
    q_keysequence_delete(actionE_xit_shortcut);
    const char* text4 = q_coreapplication_translate("MainWindow", "Tab 1");
    q_tabwidget_set_tab_text(ui->tabWidget, q_tabwidget_index_of(ui->tabWidget, ui->tab), text4);
    libqt_free(text4);
    const char* text5 = q_coreapplication_translate("MainWindow", "Dropdown:");
    q_label_set_text(ui->label, text5);
    libqt_free(text5);
    const char* text6 = q_coreapplication_translate("MainWindow", "First");
    q_combobox_set_item_text(ui->comboBox, 0, text6);
    libqt_free(text6);
    const char* text7 = q_coreapplication_translate("MainWindow", "Second");
    q_combobox_set_item_text(ui->comboBox, 1, text7);
    libqt_free(text7);
    const char* text8 = q_coreapplication_translate("MainWindow", "Number:");
    q_label_set_text(ui->label_2, text8);
    libqt_free(text8);
    const char* text9 = q_coreapplication_translate("MainWindow", "Tab 2");
    q_tabwidget_set_tab_text(ui->tabWidget, q_tabwidget_index_of(ui->tabWidget, ui->tab_2), text9);
    libqt_free(text9);
    const char* text10 = q_coreapplication_translate("MainWindow", "&File");
    q_menu_set_title(ui->menu_File, text10);
    libqt_free(text10);
    const char* text11 = q_coreapplication_translate("MainWindow", "Dock Title");
    q_dockwidget_set_window_title(ui->dockWidget, text11);
    libqt_free(text11);
}

// new_main_window_ui creates all the Qt objects for MainWindowUi
static MainWindowUi* new_main_window_ui() {
    MainWindowUi* ui = (MainWindowUi*)malloc(sizeof(MainWindowUi));
    if (ui == NULL)
        return NULL;

    ui->MainWindow = q_mainwindow_new2();
    q_mainwindow_set_object_name(ui->MainWindow, "MainWindow");
    q_mainwindow_resize(ui->MainWindow, 800, 600);

    ui->action_New = q_action_new4(ui->MainWindow);
    q_action_set_object_name(ui->action_New, "action_New");

    ui->actionE_xit = q_action_new4(ui->MainWindow);
    q_action_set_object_name(ui->actionE_xit, "actionE_xit");

    ui->centralwidget = q_widget_new(ui->MainWindow);
    q_widget_set_object_name(ui->centralwidget, "centralwidget");

    ui->gridLayout = q_gridlayout_new(ui->centralwidget);
    q_gridlayout_set_object_name(ui->gridLayout, "gridLayout");

    ui->tabWidget = q_tabwidget_new(ui->centralwidget);
    q_tabwidget_set_object_name(ui->tabWidget, "tabWidget");

    ui->tab = q_widget_new2();
    q_widget_set_object_name(ui->tab, "tab");

    ui->formLayout = q_formlayout_new(ui->tab);
    q_formlayout_set_object_name(ui->formLayout, "formLayout");

    ui->label = q_label_new(ui->tab);
    q_label_set_object_name(ui->label, "label");
    q_formlayout_set_widget(ui->formLayout, 0, QFORMLAYOUT_ITEMROLE_LABELROLE, ui->label);

    ui->comboBox = q_combobox_new(ui->tab);
    q_combobox_set_object_name(ui->comboBox, "comboBox");
    q_combobox_add_item(ui->comboBox, "");
    q_combobox_add_item(ui->comboBox, "");
    q_formlayout_set_widget(ui->formLayout, 0, QFORMLAYOUT_ITEMROLE_FIELDROLE, ui->comboBox);

    ui->label_2 = q_label_new(ui->tab);
    q_label_set_object_name(ui->label_2, "label_2");
    q_formlayout_set_widget(ui->formLayout, 1, QFORMLAYOUT_ITEMROLE_LABELROLE, ui->label_2);

    ui->spinBox = q_spinbox_new(ui->tab);
    q_spinbox_set_object_name(ui->spinBox, "spinBox");
    q_formlayout_set_widget(ui->formLayout, 1, QFORMLAYOUT_ITEMROLE_FIELDROLE, ui->spinBox);

    q_tabwidget_add_tab(ui->tabWidget, ui->tab, "");

    ui->tab_2 = q_widget_new2();
    q_widget_set_object_name(ui->tab_2, "tab_2");

    q_tabwidget_add_tab(ui->tabWidget, ui->tab_2, "");
    q_gridlayout_add_widget2(ui->gridLayout, ui->tabWidget, 0, 0);

    ui->treeWidget = q_treewidget_new(ui->centralwidget);
    q_treewidget_set_object_name(ui->treeWidget, "treeWidget");
    q_treewidget_set_frame_shape(ui->treeWidget, QFRAME_SHAPE_PANEL);
    QTreeWidgetItem* ui_treeWidget_item = q_treewidgetitem_new();
    q_treewidget_set_header_item(ui->treeWidget, ui_treeWidget_item);
    q_treewidgetitem_set_text(ui_treeWidget_item, 0, "1");
    q_gridlayout_add_widget2(ui->gridLayout, ui->treeWidget, 0, 1);

    q_mainwindow_set_central_widget(ui->MainWindow, ui->centralwidget);

    ui->menubar = q_menubar_new(ui->MainWindow);
    q_menubar_set_object_name(ui->menubar, "menubar");
    q_menubar_set_geometry(ui->menubar, 0, 0, 800, 27);

    ui->menu_File = q_menu_new(ui->menubar);
    q_menu_set_object_name(ui->menu_File, "menu_File");
    q_mainwindow_set_menu_bar(ui->MainWindow, ui->menubar);

    ui->statusbar = q_statusbar_new(ui->MainWindow);
    q_statusbar_set_object_name(ui->statusbar, "statusbar");
    q_mainwindow_set_status_bar(ui->MainWindow, ui->statusbar);

    ui->dockWidget = q_dockwidget_new(ui->MainWindow);
    q_dockwidget_set_object_name(ui->dockWidget, "dockWidget");
    q_mainwindow_add_dock_widget(ui->MainWindow, /* enum Qt__DockWidgetArea */ 1, ui->dockWidget);

    ui->dockWidgetContents = q_widget_new2();
    q_widget_set_object_name(ui->dockWidgetContents, "dockWidgetContents");

    ui->verticalLayout = q_vboxlayout_new(ui->dockWidgetContents);
    q_vboxlayout_set_object_name(ui->verticalLayout, "verticalLayout");

    ui->calendarWidget = q_calendarwidget_new(ui->dockWidgetContents);
    q_calendarwidget_set_object_name(ui->calendarWidget, "calendarWidget");

    q_vboxlayout_add_widget(ui->verticalLayout, ui->calendarWidget);
    q_dockwidget_set_widget(ui->dockWidget, ui->dockWidgetContents);

    q_menubar_add_action(ui->menubar, q_menu_menu_action(ui->menu_File));
    q_menu_add_action(ui->menu_File, ui->action_New);
    q_menu_add_separator(ui->menu_File);
    q_menu_add_action(ui->menu_File, ui->actionE_xit);

    retranslate_main_window(ui);

    return ui;
}