// Generated by libqt6c uic. To update this file, edit the .ui file in
// Qt Creator/Designer, and then run the 'uic-c' command below.
//
// uic-c -i mainwindow.ui -o mainwindow.h

#include <libqt6c.h>

/// The type definition for MainWindowUi containing all of the Qt objects
typedef struct {
    QMainWindow* MainWindow;
    QWidget* centralwidget;
    QVBoxLayout* verticalLayout;
    QPlainTextEdit* plainTextEdit;
    QGridLayout* gridLayout;
    QLabel* label_5;
    QLabel* label_3;
    QLabel* label_4;
    QSlider* pitch;
    QLabel* label_6;
    QSlider* volume;
    QComboBox* language;
    QComboBox* voice;
    QLabel* label;
    QLabel* label_2;
    QSlider* rate;
    QComboBox* engine;
    QHBoxLayout* horizontalLayout;
    QPushButton* speakButton;
    QPushButton* pauseButton;
    QPushButton* resumeButton;
    QPushButton* stopButton;
    QSpacerItem* verticalSpacer;
    QStatusBar* statusbar;
} MainWindowUi;

/// Cleanup the memory allocated for MainWindowUi and the child Qt objects
static void cleanup_main_window_ui(MainWindowUi* ui) {
    q_mainwindow_delete(ui->MainWindow);
    free(ui);
}

/// Retranslate reapplies all text translations
static void retranslate_main_window_ui(MainWindowUi* ui) {
    const char* text0 = q_coreapplication_translate("MainWindow", "MainWindow");
    q_mainwindow_set_window_title(ui->MainWindow, text0);
    libqt_free(text0);
    const char* text1 = q_coreapplication_translate("MainWindow", "Hello QtTextToSpeech,\nthis is an example text in English.\n\nQtSpeech is a library that makes text to speech easy with Qt.\nDone, over and out.");
    q_plaintextedit_set_plain_text(ui->plainTextEdit, text1);
    libqt_free(text1);
    const char* text2 = q_coreapplication_translate("MainWindow", "Engine");
    q_label_set_text(ui->label_5, text2);
    libqt_free(text2);
    const char* text3 = q_coreapplication_translate("MainWindow", "Pitch:");
    q_label_set_text(ui->label_3, text3);
    libqt_free(text3);
    const char* text4 = q_coreapplication_translate("MainWindow", "&Language:");
    q_label_set_text(ui->label_4, text4);
    libqt_free(text4);
    const char* text5 = q_coreapplication_translate("MainWindow", "Voice name:");
    q_label_set_text(ui->label_6, text5);
    libqt_free(text5);
    const char* text6 = q_coreapplication_translate("MainWindow", "Rate:");
    q_label_set_text(ui->label, text6);
    libqt_free(text6);
    const char* text7 = q_coreapplication_translate("MainWindow", "Volume:");
    q_label_set_text(ui->label_2, text7);
    libqt_free(text7);
    const char* text8 = q_coreapplication_translate("MainWindow", "Speak");
    q_pushbutton_set_text(ui->speakButton, text8);
    libqt_free(text8);
    const char* text9 = q_coreapplication_translate("MainWindow", "Pause");
    q_pushbutton_set_text(ui->pauseButton, text9);
    libqt_free(text9);
    const char* text10 = q_coreapplication_translate("MainWindow", "Resume");
    q_pushbutton_set_text(ui->resumeButton, text10);
    libqt_free(text10);
    const char* text11 = q_coreapplication_translate("MainWindow", "Stop");
    q_pushbutton_set_text(ui->stopButton, text11);
    libqt_free(text11);
}

/// new_main_window_ui creates all the Qt objects for MainWindowUi
static MainWindowUi* new_main_window_ui() {
    MainWindowUi* ui = (MainWindowUi*)malloc(sizeof(MainWindowUi));
    if (ui == NULL) {
        fprintf(stderr, "Failed to create MainWindowUi\n");
        abort();
    }

    ui->MainWindow = q_mainwindow_new2();
    q_mainwindow_set_object_name(ui->MainWindow, "MainWindow");
    q_mainwindow_resize(ui->MainWindow, 551, 448);

    ui->centralwidget = q_widget_new(ui->MainWindow);
    q_widget_set_object_name(ui->centralwidget, "centralwidget");

    ui->verticalLayout = q_vboxlayout_new(ui->centralwidget);
    q_vboxlayout_set_object_name(ui->verticalLayout, "verticalLayout");

    ui->plainTextEdit = q_plaintextedit_new(ui->centralwidget);
    q_plaintextedit_set_object_name(ui->plainTextEdit, "plainTextEdit");
    QSizePolicy* sizePolicy0 = q_sizepolicy_new3();
    q_sizepolicy_set_horizontal_policy(sizePolicy0, QSIZEPOLICY_POLICY_EXPANDING);
    q_sizepolicy_set_vertical_policy(sizePolicy0, QSIZEPOLICY_POLICY_EXPANDING);
    q_sizepolicy_set_horizontal_stretch(sizePolicy0, 0);
    q_sizepolicy_set_vertical_stretch(sizePolicy0, 0);
    QSizePolicy* plainTextEdit_sp = q_plaintextedit_size_policy(ui->plainTextEdit);
    q_sizepolicy_set_height_for_width(sizePolicy0, q_sizepolicy_has_height_for_width(plainTextEdit_sp));
    q_plaintextedit_set_size_policy(ui->plainTextEdit, sizePolicy0);
    q_sizepolicy_delete(plainTextEdit_sp);

    q_vboxlayout_add_widget(ui->verticalLayout, ui->plainTextEdit);

    ui->gridLayout = q_gridlayout_new2();
    q_gridlayout_set_object_name(ui->gridLayout, "gridLayout");

    ui->label_5 = q_label_new(ui->centralwidget);
    q_label_set_object_name(ui->label_5, "label_5");
    QSizePolicy* sizePolicy1 = q_sizepolicy_new3();
    q_sizepolicy_set_horizontal_policy(sizePolicy1, QSIZEPOLICY_POLICY_MINIMUM);
    q_sizepolicy_set_vertical_policy(sizePolicy1, QSIZEPOLICY_POLICY_PREFERRED);
    q_sizepolicy_set_horizontal_stretch(sizePolicy1, 0);
    q_sizepolicy_set_vertical_stretch(sizePolicy1, 0);
    QSizePolicy* label_5_sp = q_label_size_policy(ui->label_5);
    q_sizepolicy_set_height_for_width(sizePolicy1, q_sizepolicy_has_height_for_width(label_5_sp));
    q_label_set_size_policy(ui->label_5, sizePolicy1);
    q_sizepolicy_delete(label_5_sp);
    q_label_set_alignment(ui->label_5, QT_ALIGNMENTFLAG_ALIGNRIGHT | QT_ALIGNMENTFLAG_ALIGNTRAILING | QT_ALIGNMENTFLAG_ALIGNVCENTER);
    q_gridlayout_add_widget2(ui->gridLayout, ui->label_5, 4, 0);

    ui->label_3 = q_label_new(ui->centralwidget);
    q_label_set_object_name(ui->label_3, "label_3");
    QSizePolicy* label_3_sp = q_label_size_policy(ui->label_3);
    q_sizepolicy_set_height_for_width(sizePolicy1, q_sizepolicy_has_height_for_width(label_3_sp));
    q_label_set_size_policy(ui->label_3, sizePolicy1);
    q_sizepolicy_delete(label_3_sp);
    q_label_set_alignment(ui->label_3, QT_ALIGNMENTFLAG_ALIGNRIGHT | QT_ALIGNMENTFLAG_ALIGNTRAILING | QT_ALIGNMENTFLAG_ALIGNVCENTER);
    q_gridlayout_add_widget2(ui->gridLayout, ui->label_3, 3, 0);

    ui->label_4 = q_label_new(ui->centralwidget);
    q_label_set_object_name(ui->label_4, "label_4");
    QSizePolicy* label_4_sp = q_label_size_policy(ui->label_4);
    q_sizepolicy_set_height_for_width(sizePolicy1, q_sizepolicy_has_height_for_width(label_4_sp));
    q_label_set_size_policy(ui->label_4, sizePolicy1);
    q_sizepolicy_delete(label_4_sp);
    q_label_set_alignment(ui->label_4, QT_ALIGNMENTFLAG_ALIGNRIGHT | QT_ALIGNMENTFLAG_ALIGNTRAILING | QT_ALIGNMENTFLAG_ALIGNVCENTER);
    q_gridlayout_add_widget2(ui->gridLayout, ui->label_4, 5, 0);

    ui->pitch = q_slider_new(ui->centralwidget);
    q_slider_set_object_name(ui->pitch, "pitch");
    q_slider_set_minimum(ui->pitch, -10);
    q_slider_set_maximum(ui->pitch, 10);
    q_slider_set_single_step(ui->pitch, 1);
    q_slider_set_orientation(ui->pitch, QT_ORIENTATION_HORIZONTAL);
    q_gridlayout_add_widget2(ui->gridLayout, ui->pitch, 3, 2);

    ui->label_6 = q_label_new(ui->centralwidget);
    q_label_set_object_name(ui->label_6, "label_6");
    q_label_set_alignment(ui->label_6, QT_ALIGNMENTFLAG_ALIGNRIGHT | QT_ALIGNMENTFLAG_ALIGNTRAILING | QT_ALIGNMENTFLAG_ALIGNVCENTER);
    q_gridlayout_add_widget2(ui->gridLayout, ui->label_6, 6, 0);

    ui->volume = q_slider_new(ui->centralwidget);
    q_slider_set_object_name(ui->volume, "volume");
    q_slider_set_maximum(ui->volume, 100);
    q_slider_set_single_step(ui->volume, 5);
    q_slider_set_page_step(ui->volume, 20);
    q_slider_set_value(ui->volume, 70);
    q_slider_set_orientation(ui->volume, QT_ORIENTATION_HORIZONTAL);
    q_gridlayout_add_widget2(ui->gridLayout, ui->volume, 1, 2);

    ui->language = q_combobox_new(ui->centralwidget);
    q_combobox_set_object_name(ui->language, "language");
    QSizePolicy* sizePolicy2 = q_sizepolicy_new3();
    q_sizepolicy_set_horizontal_policy(sizePolicy2, QSIZEPOLICY_POLICY_EXPANDING);
    q_sizepolicy_set_vertical_policy(sizePolicy2, QSIZEPOLICY_POLICY_FIXED);
    q_sizepolicy_set_horizontal_stretch(sizePolicy2, 0);
    q_sizepolicy_set_vertical_stretch(sizePolicy2, 0);
    QSizePolicy* language_sp = q_combobox_size_policy(ui->language);
    q_sizepolicy_set_height_for_width(sizePolicy2, q_sizepolicy_has_height_for_width(language_sp));
    q_combobox_set_size_policy(ui->language, sizePolicy2);
    q_sizepolicy_delete(language_sp);
    q_gridlayout_add_widget2(ui->gridLayout, ui->language, 5, 2);

    ui->voice = q_combobox_new(ui->centralwidget);
    q_combobox_set_object_name(ui->voice, "voice");
    q_gridlayout_add_widget2(ui->gridLayout, ui->voice, 6, 2);

    ui->label = q_label_new(ui->centralwidget);
    q_label_set_object_name(ui->label, "label");
    QSizePolicy* label_sp = q_label_size_policy(ui->label);
    q_sizepolicy_set_height_for_width(sizePolicy1, q_sizepolicy_has_height_for_width(label_sp));
    q_label_set_size_policy(ui->label, sizePolicy1);
    q_sizepolicy_delete(label_sp);
    q_label_set_alignment(ui->label, QT_ALIGNMENTFLAG_ALIGNRIGHT | QT_ALIGNMENTFLAG_ALIGNTRAILING | QT_ALIGNMENTFLAG_ALIGNVCENTER);
    q_gridlayout_add_widget2(ui->gridLayout, ui->label, 2, 0);

    ui->label_2 = q_label_new(ui->centralwidget);
    q_label_set_object_name(ui->label_2, "label_2");
    QSizePolicy* label_2_sp = q_label_size_policy(ui->label_2);
    q_sizepolicy_set_height_for_width(sizePolicy1, q_sizepolicy_has_height_for_width(label_2_sp));
    q_label_set_size_policy(ui->label_2, sizePolicy1);
    q_sizepolicy_delete(label_2_sp);
    q_label_set_alignment(ui->label_2, QT_ALIGNMENTFLAG_ALIGNRIGHT | QT_ALIGNMENTFLAG_ALIGNTRAILING | QT_ALIGNMENTFLAG_ALIGNVCENTER);
    q_gridlayout_add_widget2(ui->gridLayout, ui->label_2, 1, 0);

    ui->rate = q_slider_new(ui->centralwidget);
    q_slider_set_object_name(ui->rate, "rate");
    q_slider_set_minimum(ui->rate, -10);
    q_slider_set_maximum(ui->rate, 10);
    q_slider_set_orientation(ui->rate, QT_ORIENTATION_HORIZONTAL);
    q_gridlayout_add_widget2(ui->gridLayout, ui->rate, 2, 2);

    ui->engine = q_combobox_new(ui->centralwidget);
    q_combobox_set_object_name(ui->engine, "engine");
    QSizePolicy* engine_sp = q_combobox_size_policy(ui->engine);
    q_sizepolicy_set_height_for_width(sizePolicy2, q_sizepolicy_has_height_for_width(engine_sp));
    q_combobox_set_size_policy(ui->engine, sizePolicy2);
    q_sizepolicy_delete(engine_sp);
    q_gridlayout_add_widget2(ui->gridLayout, ui->engine, 4, 2);

    q_vboxlayout_add_layout(ui->verticalLayout, ui->gridLayout);

    ui->horizontalLayout = q_hboxlayout_new2();
    q_hboxlayout_set_object_name(ui->horizontalLayout, "horizontalLayout");

    ui->speakButton = q_pushbutton_new(ui->centralwidget);
    q_pushbutton_set_object_name(ui->speakButton, "speakButton");

    q_hboxlayout_add_widget(ui->horizontalLayout, ui->speakButton);

    ui->pauseButton = q_pushbutton_new(ui->centralwidget);
    q_pushbutton_set_object_name(ui->pauseButton, "pauseButton");
    q_pushbutton_set_enabled(ui->pauseButton, false);

    q_hboxlayout_add_widget(ui->horizontalLayout, ui->pauseButton);

    ui->resumeButton = q_pushbutton_new(ui->centralwidget);
    q_pushbutton_set_object_name(ui->resumeButton, "resumeButton");
    q_pushbutton_set_enabled(ui->resumeButton, false);

    q_hboxlayout_add_widget(ui->horizontalLayout, ui->resumeButton);

    ui->stopButton = q_pushbutton_new(ui->centralwidget);
    q_pushbutton_set_object_name(ui->stopButton, "stopButton");

    q_hboxlayout_add_widget(ui->horizontalLayout, ui->stopButton);

    q_vboxlayout_add_layout(ui->verticalLayout, ui->horizontalLayout);

    ui->verticalSpacer = q_spaceritem_new4(20, 40, QSIZEPOLICY_POLICY_MINIMUM, QSIZEPOLICY_POLICY_EXPANDING);
    q_vboxlayout_add_item(ui->verticalLayout, ui->verticalSpacer);

    q_mainwindow_set_central_widget(ui->MainWindow, ui->centralwidget);

    ui->statusbar = q_statusbar_new(ui->MainWindow);
    q_statusbar_set_object_name(ui->statusbar, "statusbar");
    q_mainwindow_set_status_bar(ui->MainWindow, ui->statusbar);

    q_sizepolicy_delete(sizePolicy0);
    q_sizepolicy_delete(sizePolicy1);
    q_sizepolicy_delete(sizePolicy2);
    q_label_set_buddy(ui->label_4, ui->language);
    q_widget_set_tab_order(ui->plainTextEdit, ui->speakButton);
    q_widget_set_tab_order(ui->speakButton, ui->pauseButton);
    q_widget_set_tab_order(ui->pauseButton, ui->resumeButton);
    q_widget_set_tab_order(ui->resumeButton, ui->stopButton);

    retranslate_main_window_ui(ui);

    return ui;
}